#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct Object {
    int index;
    char name[100];
    float area; 
    float power;
    float price;
} object;


void showSolarPanel(object *sp, int index) {
    printf("\n---------------------------------\n");
    printf(" \n Solar panel #%d\n", index + 1);
    printf("%s\n", sp[index].name);
    printf("Area: %.2f\n", sp[index].area);
    printf("Power Generated: %.2f\n", sp[index].power);
    printf("Price: %.2f\n", sp[index].price);
    printf("\n---------------------------------\n");
}

void showWaterTurbine(object *wt, int index) {
    printf("\n---------------------------------\n");
    printf(" \n Water turbine #%d\n", index + 1);
    printf("%s\n", wt[index].name);
    printf("Power Generated: %.2f\n", wt[index].power);
    printf("Price: %.2f\n", wt[index].price);
    printf("\n---------------------------------\n");
}

void showWindTurbine(object *wt, int index){
    printf("\n---------------------------------\n");
    printf(" \n Wind turbine #%d\n", index + 1);
    printf("%s\n",  wt[index].name);
    printf("Area: %.2f\n", wt[index].area);
    printf("Power Generated: %.2f\n", wt[index].power);
    printf("Price: %.2f\n", wt[index].price);
    printf("\n---------------------------------\n");
}

void addObj(object *obj, int index, char name[100], float area, float power, float price) {
    strcpy(obj->name, name);
    obj->index = index;
    obj->area = area;
    obj->power = power;
    obj->price = price;
}

void removeObj(object *obj, int index, int *sum) {
    if (index-1 == *sum) {
        (*sum)--;
    } else {
        for(int i = index; i < *sum; i++) {
            obj[i] = obj[i+1];
            (*sum)--;
        }
    }
}

int main() {
    //The states of the simulator program
    int one = 1;

    float usableArea; // Initial usable area
    float totalArea = 0; // Total area covered by added components
    float needPower; //Power needed per hour in kilowatt per hour
    float totalPower= 0; //Power generated by the generators
    float money;

    //The generators that are available in this program
    object *sp = calloc(100, sizeof(object));
    object *wt = calloc(100, sizeof(object));
    object *wn = calloc(100, sizeof(object));

    int spCounter = 0;
    int wtCounter = 0;
    int wnCounter = 0;

    float spPower = 0;
    float wtPower = 0;
    float wnPower = 0;
    totalPower = spPower + wtPower + wnPower;

    //variables to temporarily store fields to be inserted
    int input = 0;
    char name[100];
    float area;
    float power; // Kilowatt per hour
    float price; // in dollars

    printf("Enter the initial usable area in km squared: ");
    scanf("%f", &usableArea);
    printf("Enter the needed power in kwh: ");
    scanf("%f", &needPower);
    printf("Enter the initial money you have in dollars: ");
    scanf("%f", &money);

    while (one == 1) {
        input = 0;
        printf("Usable Area: %.2f\n", usableArea - totalArea);
        printf("Needed Power: %.2f\n", needPower - totalPower);
        printf("Money left: %.2f\n", money);
        if (usableArea == 0) {
            printf("You have no more area to build!\n");
        }
        if (money == 0) {
            printf("You have no more money to spend!\n");
        }
        if (needPower <= totalPower) {
            printf("You have fullfilled the energy needed!\n");
        }
        if (spCounter > 0) {
            printf("Solar Panels:\n");
            for (int i = 0; i < spCounter; i++) {
                showSolarPanel(sp, i);
            }
        }
        if (wtCounter > 0) {
            printf("Water Turbines:\n");
            for (int i = 0; i < wtCounter; i++) {
                showWaterTurbine(wt, i);
            }
        }
        if (wnCounter > 0) {
            printf("Wind Turbines:\n");
            for (int i = 0; i < wnCounter; i++) {
                showWindTurbine(wn, i);
            }
        }

        printf("\n BUILD MENU \n");
        printf(" 1. Add Solar Panel \n");
        printf(" 2. Add Water Turbine \n");
        printf(" 3. Add Wind Turbine \n");
        printf(" 4. Remove Solar Panel \n");
        printf(" 5. Remove Water Turbine \n");
        printf(" 6. Remove Wind Turbine \n");
        printf(" 9. show the current data \n");
        printf(" 0. Done Input \n");
        printf(" Enter your choice: ");

        scanf("%d", &input);
        
        switch (input) {
            case 1: {
                if (usableArea == 0 || money == 0) {
                    printf("You cannot build more generators!\n");
                    break;
                } else {
                    printf("\n Enter details for Solar Panel:\n");
                    printf("Name: ");
                    scanf(" %[^\n]", name);
                    printf("Area (in Kilometer squared): ");
                    scanf("%f", &area);
                    printf("Power (in Kilowatt): ");
                    scanf("%f", &power);
                    printf("Price: ");
                    scanf("%f", &price);

                    if (usableArea - area <= 0) {
                        printf("You have no more area to build!\n");
                        break;
                    } else if (money - price <= 0) {
                        printf("You cannot afford this generator!\n");
                        break;
                    } else {
                        addObj(sp, spCounter, name, area, power, price);
                        spPower += power;  
                        totalArea += area;
                        spCounter++;
                    }
                } break;
            } break;
            case 2: {
                if (usableArea == 0 || money == 0) {
                    printf("You cannot build more generators!\n");
                    break;
                } else {
                    printf("\n Enter details for Water Turbine:\n");
                    printf("Name: ");
                    scanf(" %[^\n]", name);
                    printf("Area (in Kilometer squared): ");
                    scanf("%f", &area);
                    printf("Power (in Kilowatt): ");
                    scanf("%f", &power);
                    printf("Price: ");
                    scanf("%f", &price);

                    if (usableArea - area <= 0) {
                        printf("You have no more area to build!\n");
                        break;
                    } else if (money - price <= 0) {
                        printf("You cannot afford this generator!\n");
                        break;
                    } else {
                        addObj(wt, wtCounter, name, area, power, price);
                        wtPower += power;  
                        totalArea += area;
                        wtCounter++;
                    }
                } break;
            } break;
            case 3: {
                if (usableArea == 0 || money == 0) {
                    printf("You cannot build more generators!\n");
                    break;
                } else {
                    printf("\n Enter details for Wind Turbine:\n");
                    printf("Name: ");
                    scanf(" %[^\n]", name);
                    printf("Area (in Kilometer squared): ");
                    scanf("%f", &area);
                    printf("Power (in Kilowatt): ");
                    scanf("%f", &power);
                    printf("Price: ");
                    scanf("%f", &price);

                    if (usableArea - area <= 0) {
                        printf("You have no more area to build!\n");
                        break;
                    } else if (money - price <= 0) {
                        printf("You cannot afford this generator!\n");
                        break;
                    } else {
                        addObj(wn, wnCounter, name, area, power, price);
                        wnPower += power;  
                        totalArea += area;
                        wnCounter++;
                    }
                } break;
            } break;
            case 4: {
                if (spCounter <= 0) {
                    printf("You have no solar panels. \n");
                    break;
                } else {
                    for (int i = 0; i < spCounter; i++) {
                        showSolarPanel(sp,i);
                    }
                    printf("Type the index of the solar panel to be removed: \n");
                    printf("Please enter any minus integer to cancel deleting \n");
                    scanf("%d", &input);
                    if (input < 0) {
                        printf("Cancelling operation. \n");
                        break;
                    } else if (input >= spCounter) {
                        printf("Index not found. \n");
                    } else {
                        removeObj(sp, input-1, &spCounter);
                    }
                }
            }break;

            case 5: {
                if (wtCounter <= 0) {
                    printf("You have no solar panels. \n");
                    break;
                } else {
                    for (int i = 0; i < wtCounter; i++) {
                        showWaterTurbine(wt,i);
                    }
                    printf("Type the index of the solar panel to be removed: \n");
                    printf("Please enter any minus integer to cancel deleting \n");
                    scanf("%d", &input);
                    if (input < 0) {
                        printf("Cancelling operation. \n");
                        break;
                    } else if (input >= wtCounter) {
                        printf("Index not found. \n");
                    } else {
                        removeObj(wt, input-1, &wtCounter);
                    }
                }
            }break;

            case 6: {
                if (wnCounter <= 0) {
                    printf("You have no solar panels. \n");
                    break;
                } else {
                    for (int i = 0; i < wnCounter; i++) {
                        showWindTurbine(wn,i);
                    }
                    printf("Type the index of the solar panel to be removed: \n");
                    printf("Please enter any minus integer to cancel deleting \n");
                    scanf("%d", &input);
                    if (input < 0) {
                        printf("Cancelling operation. \n");
                        break;
                    } else if (input >= wnCounter) {
                        printf("Index not found. \n");
                    } else {
                        removeObj(wn, input-1, &wnCounter);
                    }
                }
            }break;

            case 9:{
                printf("-------------------");

                printf("\nCurrent Data:\n");
                printf("Energy Needed: %.2f KWh\n", needPower);
                printf("Usable Area: %.2f\n", usableArea - totalArea);

                printf("------------------- \n \n");
                break;
            }
            case 0:
                one = 0;
                break;
        }
    }
    free(sp);
    free(wt);
    free(wn);
    return 0;
}